name: Build Global

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch:
    inputs:
      build_kernel_op8_oos131_a13:
        description: 'Build Kernel OnePlus 8 (OOS13.1)?'
        required: true
        type: boolean
        default: true
      build_kernel_k20p_aosp_a15:
        description: 'Build Kernel Redmi K20Pro (Soviet-Star-OSS)(Based-AOSP A15)?'
        required: true
        type: boolean
        default: true
      build_kernel_mix2s_evox_a15:
        description: 'Build Kernel Xiaomi Mix2s (EVOX-A15-Official)?'
        required: true
        type: boolean
        default: true

jobs:
  build_kernel_op8_oos131_a13:
    uses: ./.github/workflows/build_kernel_op8_oos13.1_a13.yml
    secrets: inherit
    if: ${{ inputs.build_kernel_op8_oos131_a13 == 'true' }}

  build_kernel_k20p_aosp_a15:
    uses: ./.github/workflows/build_kernel_k20p_aosp_a15.yml
    secrets: inherit
    if: ${{ inputs.build_kernel_k20p_aosp_a15 == 'true' }}

  build_kernel_mix2s_evox_a15:
    uses: ./.github/workflows/build_kernel_mix2s_evox_a15.yml
    secrets: inherit
    if: ${{ inputs.build_kernel_mix2s_evox_a15 == 'true' }}